### ISSUE TITLE
Remove dependency on `xclip` or `xsel` for copy and paste support on Linux

### ISSUE THREAD

**Issue by andreynering** [charmbracelet/crush#1188]
### Description

* Follow-up of #661

We use [github.com/atotto/clipboard](https://github.com/atotto/clipboard) to have clipboard support. It should work 100% of the time on macOS and Windows, but for Linux it requires `xclip` or `xsel` to be installed.

This issue is to figure it out a way to ensure 100% support for clipboard on Linux.

### Environment

Linux

**Comment by phplego** [comment]
I suggest to start with describing all UI places/actions where the clipboard is used in Crush.
To understand which cases are essential and reapprove reasons why we need extra clipboard interactions on top of default terminal behavior

**Comment by phplego** [comment]
Another thought that I would like to share is the error handling.

It would be proper to verify that the text is successfully set to the clipboard here
https://github.com/charmbracelet/crush/blob/255aa3bcaaa79a270b48da607b2adab6a7e89bbd/internal/tui/components/chat/chat.go#L767

and call the m.SelectionClear() ONLY if it was successful (and maybe to display an error otherwise).

**UPD**
I see that the code uses both OSC 52 seq and native clipboard paste (via https://github.com/atotto/clipboard). And it's not so obvious how to check if all of them failed, since getting text from clipboard again may be tricky - there is more than one way to do it.

As for me, the simplest solution in this situation is

- Don't display success message (since we don't know was it successful or not)
- Never call m.SelectionClear() - let the user control it.

**Comment by peachkeel** [comment]
Hi @phplego and @andreynering! I've moved over here from #661.

I discovered that the X11 paste issue was supposedly fixed in charmbracelet/bubbletea#1086.

My `xterm` seems to have OSC 52 support, so I don't understand why paste isn't working.

**Comment by peachkeel** [comment]
After further investigation, it seems like `crush` is acting like `tmux`.

* **Problem:** When `crush` starts, it captures all mouse events to handle its internal features (like selecting text in a pane). This overrides your terminal's default behavior, so middle-click-to-paste is "eaten" by the app and does nothing.
* **Solution:** You must hold `Shift` to bypass the application's mouse control.
    * **To Select (Terminal-Style):** Hold `Shift` + **Left-click** and Drag.
    * **To Paste:** Hold `Shift` + **Middle-click** in the text input area.

cc @phplego @andreynering

**Comment by dreh23** [comment]
This is still really annoying.  The mentioned workaround works subpar, because it also copies over all the ascii symbols from crush, meaning multi-line copy/paste always ends up being a mess.  I use terminator mostly, but all my ubuntu terminals are behaving the same in this regard.

**Comment by gavmor** [comment]
Also hitting this on crush v0.91.2, with a slightly different trigger than what's described above:

- Selection was done via **arrow keys** (`Chat`'s keyboard highlight), not mouse-drag — so this isn't limited to the mouse-capture/Shift-to-bypass case discussed above. `c`/`y` still shows the "Copied!" toast.
- Setup: crush running inside a tmux pane managed by a session manager (Agent of Empires / `aoe`), on a local X11 desktop (not SSH/remote) — DISPLAY and XAUTHORITY are correctly forwarded to the pane.
- Confirmed this isn't an environment/X11 misconfiguration on our end:
  - crush's own startup log shows `clipboard.Init()` succeeding (no "Clipboard initialization failed" warning).
  - Immediately after pressing `c`, `xclip -o -selection clipboard` on the same DISPLAY comes back empty.
  - A plain `echo foo | xclip -selection clipboard` / `xclip -o -selection clipboard` round-trip on the exact same DISPLAY/XAUTHORITY at the same time works correctly.

So the toast really does fire independent of whether the write landed, as already noted here — in our case the underlying X11 connection is healthy and the write still doesn't reach the CLIPBOARD selection. +1 for making the success message conditional on a verified write (or just dropping it, as suggested above).
