### ISSUE TITLE
Termux package fails to install

### ISSUE THREAD

**Issue by IamN4m3l3ss** [charmbracelet/crush#793]
### Describe the bug

Trying to install the termux.deb package with dpkg returns this error:
```
❯ dpkg -i crush_0.6.2_aarch64.deb.termux.deb
(Reading database ... 30057 files and directories currently installed.)
Preparing to unpack crush_0.6.2_aarch64.deb.termux.deb ...
Unpacking crush (0.6.2) over (0.6.2) ...
dpkg: error processing archive crush_0.6.2_aarch64.deb.termux.deb (--install):
 error creating directory './etc/bash_completion.d': Read-only file system
dpkg: error while cleaning up:
 unable to remove newly-extracted version of '/etc/bash_completion.d': Read-only file system
Errors were encountered while processing:
 crush_0.6.2_aarch64.deb.termux.deb
```

### Setup

Please complete the following information along with version numbers, if applicable.
 - OS: Android 15
 - Shell: Zsh
 - Terminal Emulator: Termux
 - Terminal Multiplexer: tmux

### To Reproduce

1. Open termux
2. Try to install package with dpkg
3. dpkg -i crush.deb

### Expected behavior

For it to install properly instead of trying to install into root.
(Proper path \/)
```
$PREFIX ==> /data/data/com.termux/files/usr

$PREFIX/bin
$PREFIX/lib
$PREFIX/etc
$PREFIX/tmp
```

**Comment by caarlos0** [comment]
is the prefix with or without the `/usr`? 

E.g., is it `/data/data/com.termux/files/usr/lib` or `/data/data/com.termux/files/lib`?

See: #822

**Comment by IamN4m3l3ss** [comment]
> is the prefix with or without the `/usr`?
> 
> E.g., is it `/data/data/com.termux/files/usr/lib` or `/data/data/com.termux/files/lib`?
> 
> See: [#822](https://github.com/charmbracelet/crush/pull/822)

$PREFIX/lib points towards /data/data/com.termux/files/usr/lib
It's just like how you normally would navigate directories. 
https://wiki.termux.com/wiki/Getting_started

**Comment by andreynering** [comment]
Hi @IamN4m3l3ss,

This should be fixed in [v0.7.1](https://github.com/charmbracelet/crush/releases/tag/v0.7.1). Let me know if that works for you.

**Comment by IamN4m3l3ss** [comment]
@andreynering 
![Image](https://github.com/user-attachments/assets/1e0f6933-c031-4333-b5ab-e2032fc97a7a)

It installed properly(?) However I'm getting this error now. I've looked around already (#453), however connectivity to catwalk shouldn't be blocked. I tried on both Wi-Fi and data; maybe it's something with Termux? I have no clue.

**Comment by andreynering** [comment]
Maybe it's some kind of security restriction from Android, but I'm just guessing...

**Comment by IamN4m3l3ss** [comment]
Ping works on github and catwalk, so that couldn't be it right?
I suppose I'll wait for 453,  can't really do anything else to debug this.

**Comment by IamN4m3l3ss** [comment]
@andreynering

I think I figured it out: the `provider.go` file doesn't exist because it's still not completely installing properly and/or setting things up at first launch.

I found the log file when I was messing with Termux.
```
{"time":"2025-08-21T19:31:35.151267844Z","level":"INFO","source":{"function":"github.com/charmbracelet/crush/internal/config.loadProviders","file":"/home/runner/work/crush/crush/internal/config/provider.go","line":113},"msg":"Getting live provider data"}
``` 
I don't know exactly where it's checking (Termux or root), but there is no runner folder in Termux's home directory, so I assume the latter, which is $HOME or /data/data/com.termux/files/home.

I also noticed it made a new etc folder with the bash_completion.d file in termux/files instead of termux/files/usr/etc.

However, there's always the possibility to install a Linux distro on Termux with proot-distro and use crush that way (if anyone using Termux is reading this and encountering the same problem).

**Comment by caarlos0** [comment]
> I think I figured it out: the provider.go file doesn't exist because it's still not completely installing properly and/or setting things up at first launch.

that file shouldn't exist if you installed a pre-compiled package, as it only contains the pre-compiled binaries.

> I don't know exactly where it's checking (Termux or root), but there is no runner folder in Termux's home directory, so I assume the latter, which is $HOME or /data/data/com.termux/files/home.

`/home/runner` not a path in your installation, its the path when it was built (GitHub actions).

I think what might be happening is:

1. either termux doesn't have perms to network calls for some reason
2. or, it's trying to cache things to a folder it doesn't have permissions to write/doesn't exist

Could you try starting crush with `--debug` and then check the logs?


> I also noticed it made a new etc folder with the bash_completion.d file in termux/files instead of termux/files/usr/etc.

fixed in 9d9372038e6b14907cdd71710e993bf9c71d3646

**Comment by IamN4m3l3ss** [comment]
I tried with `--debug` but there's nothing else other than what i send earlier.
I can ping both domains just fine and crush works fine when running arch with proot-distro in termux.
So definitely not a network issue.

[crush.log](https://github.com/user-attachments/files/21968905/crush.log)

Edit:
I tried running `crush logs` and that returned this error: 
`Failed to load configuration: failed to load providers: failed to load providers.`
Still nothing else in the log file tho.

**Comment by caarlos0** [comment]
made some changes towards helping debugging this: #884 & #885
